name: adras-hazus
channels:
  - conda-forge
dependencies:
  - python=3.9
  - python-wget=3.2
  - rasterio=1.3.2
  - geopandas=0.11.1
  - netCDF4=1.6.1
  - matplotlib=3.6.0
  - pandas=1.5.0
  - numpy=1.23.3
  - xarray=2022.6.0
  - pyyaml=6.0.0
  - boto3=1.24.76
  - affine=2.3.1
  - colour=0.1.5
  - cartopy=0.21.0
  - contextily=1.2.0
  - Pillow=9.2.0
  - gdal=3.5.2
