# A slightly different format than used for our typical ADCIRC thredds calls

DEFAULT: &default
  RDIR: $RUNTIMEDIR
  LOGGING: true
  LOGLEVEL: DEBUG
  GRAPHICS: true

S3:
  SEND2AWS: false
  BucketName: 'hazus'
  RegionName: 'us-east-2' 

VARFILEMAP: &varfilemap
  zeta_max: 'maxele.63.nc'
  vel_max: 'maxvel.63.nc'
  inun_max: 'maxinundepth.63.nc'
  zeta: 'fort.63.nc'

