# A slightly different format than used for our typical ADCIRC thredds calls

DEFAULT: &default
  RDIR: $RUNTIMEDIR
  LOGGING: true
  LOGLEVEL: INFO
  GRAPHICS: true
  SEND2AWS: true

ADCIRC: &adcirc
  AdcircGrid: 'hsofs'
  Machine: 'hatteras.renci.org'
  NodeList: 'adcirc_test_nodes.dat'
  Instance: "hsofs-nam-bob"  #  "ncfs-dev-hsofs-nam-master"
  baseurl: 'http://tds.renci.org:8080/thredds/'
  catPart: '/catalog/2020/nam/catalog.xml'
  dodsCpart: '/dodsC/%s/nam/%s/%s/%s/%s/%s/%s'
  fortNumber: '63'

REGRID: &regrid
  DEFAULT:
    upperleft_lo: -77.09
    upperleft_la: 35.7
    res: 100  # resolution in deg
    nx: 1000
    ny: 1000
    target_crs: 'epsg:6346'
    adcirc_crs: 'epsg:4326'
  nc_inundation_v9.99_w_rivers:
    upperleft_lo: -78.25
    upperleft_la: 34.5
    res: 100  # resolution in deg
    nx: 1000
    ny: 1000
    target_crs: 'epsg:6346'
    adcirc_crs: 'epsg:4326'

VARFILEMAP: &varfilemap
  zeta_max: 'maxele.63.nc'
  vel_max: 'maxvel.63.nc'
  inun_max: 'maxinundepth.63.nc'
  zeta: 'fort.63.nc'

TIME: &time
  doffset: 0
  hoffset: -6
  period: 6

GRAPHICS: &graphics
  CMAP: "bwr"
  NCOL: 20
  VMIN: -0.5
  VMAX: 0.5
  MAPRES: "i"

